Dev Org/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>EngineeringReqNumber__c</fullName>
        <label>Engineering Req Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PotentialLiability__c</fullName>
        <label>Potential Liability</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>GC1040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC1060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC3060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5040</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC5060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GC1020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLAViolation__c</fullName>
        <label>SLA Violation</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Dev Org/src/classes/SearcDisplayRecordsCls.cls
global class SearcDisplayRecordsCls{
    webservice static String SearcDisplayRecords(String accName){
    string output='';
    
     // List<Account> accList =[Select a.Name, a.Id,a.phone, (Select Id, CaseNumber, SuppliedName, Status From Cases) From Account a where a.Name =:accName];
       string qry='Select Name,phone from Account where name !=null';
        if(accName!=''){
        qry +=' AND Name Like ' +'\''+'%'+accName+'%'+'\'';
        }
        System.debug('qry is:'+qry);
        List<Account> accList = Database.Query(qry);
      

    output= JSON.serialize(accList);
    return output;
    }
    webservice static String DisplayRecords(){
    string output='';
       List<Case> CasesList =[Select Id, IsDeleted, CaseNumber, ContactId, AccountId, AssetId, ParentId, SuppliedName, SuppliedEmail, SuppliedPhone, SuppliedCompany, Type, Status, Reason, Origin, Subject, Priority, Description, IsClosed, ClosedDate, IsEscalated, OwnerId, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, EngineeringReqNumber__c, SLAViolation__c, Product__c, PotentialLiability__c FROM Case ];
       output= JSON.serialize(CasesList);
    return output;
    }
   
}