Dev Org/src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev Org/src/objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev Org/src/objects/Page_Section__c.object
<CustomObject>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Page-Sections</relationshipLabel>
        <relationshipName>Page_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Page-Sections</relationshipLabel>
        <relationshipName>Page_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Root__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root</label>
        <referenceTo>Page_Section__c</referenceTo>
        <relationshipLabel>Page-Sections</relationshipLabel>
        <relationshipName>Page_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Page-Sections</relationshipLabel>
        <relationshipName>Page_Sections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Page-Section</label>
    <nameField>
        <label>Page-Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page-Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev Org/src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev Org/src/objects/Question_Section_Branching__c.object
<CustomObject>
    <label>Question Section Branching</label>
    <nameField>
        <label>Question Section Branching Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Section Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev Org/src/objects/Section__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev Org/src/objects/Section_Question__c.object
<CustomObject>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Section-Questions</relationshipLabel>
        <relationshipName>Section_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Section-Questions</relationshipLabel>
        <relationshipName>Section_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Root__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root</label>
        <referenceTo>Section_Question__c</referenceTo>
        <relationshipLabel>Section-Questions</relationshipLabel>
        <relationshipName>Section_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Section</label>
        <referenceTo>Section__c</referenceTo>
        <relationshipLabel>Section-Questions</relationshipLabel>
        <relationshipName>Section_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Section-Question</label>
    <nameField>
        <label>Section-Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Section-Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev Org/src/objects/Template__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev Org/src/objects/Template_Page__c.object
<CustomObject>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Template_Pages</relationshipLabel>
        <relationshipName>Template_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Page</label>
        <referenceTo>Page__c</referenceTo>
        <relationshipLabel>Template_Pages</relationshipLabel>
        <relationshipName>Template_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Root__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root</label>
        <referenceTo>Template_Page__c</referenceTo>
        <relationshipLabel>Template_Pages</relationshipLabel>
        <relationshipName>Template_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>Template__c</referenceTo>
        <relationshipLabel>Template_Pages</relationshipLabel>
        <relationshipName>Template_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Template-Page</label>
    <nameField>
        <label>Template-Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template_Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev Org/src/classes/FormTriggerHandler.cls
public class FormTriggerHandler {

      // This method is used to clone the Page, sections, question junctions object from tempalte and associate to form
     public void cloneTemplate(List<Form__c> igforms)
     {
         Map<ID,Form__c> tempIdFormMap = new Map<ID,Form__c>();
         List<Template_Page__c> tempPageList = new List<Template_Page__c>();
         List<Page_Section__c> pageSecList = new List<Page_Section__c>();
         List<Section_Question__c> secQNList = new List<Section_Question__c>();                  
         //List<Question_Section_Branching__c> qnSecBranchList = new List<Question_Section_Branching__c>();
         Set<ID> pageIds = new Set<ID>();
         Set<ID> sectionIds = new Set<ID>();
         Map<ID,ID> pageSecOldNewmap = new Map<ID,ID>();
         Map<ID,ID> temPageOldNewmap = new Map<ID,ID>();
         Map<ID,ID> secQuesOldNewmap = new Map<ID,ID>();
         ID formID;
         

                                    
         if( igforms.size()>0)       
         {         
         Savepoint sp = Database.setSavepoint(); // Roll back if any of the dml operation fails
         try {
         formID = igforms[0].id;
         
                             
         //ID RecTypeId = Schema.SObjectType.Template_Page__c.getRecordTypeInfosByName().get('Template Page').getRecordTypeId();
         
         for (Template_Page__c tempPage :[Select Id, Form__c,Root__c,Template__c, Status__c, Name, Display_Name__c,Sort_Order__c, Page__c From Template_Page__c WHERE Template__c=:igforms[0].Template__c AND Form__c=null ORDER BY Sort_Order__c])
         {
             Template_Page__c tpj = tempPage.Clone(false,true);
             //tpj.RecordTypeId = Schema.SObjectType.Template_Page__c.getRecordTypeInfosByName().get('Form Page').getRecordTypeId();
             tpj.Status__c = 'Not Started';
             tpj.Root__c = tempPage.id;
             tpj.Form__c = formID;             
             pageIds.add(tempPage.Page__c);
             tempPageList.add(tpj);                                   
         }
                           
         if(tempPageList.size()>0)
         {
             system.debug ('##tempPageList: '+tempPageList);
             insert tempPageList;
         }
         
         for (Template_Page__c tempPageInserted :[Select Id, Form__c, Root__c,Template__c, Name, Display_Name__c,Sort_Order__c, Page__c From Template_Page__c WHERE Form__c=:formID  ORDER BY Sort_Order__c])
         {
             temPageOldNewmap.put(tempPageInserted.Root__c,tempPageInserted.Id);
         }

         
         for(Page_Section__c pageSec:[Select Id, Sort_Order__c, Root__c,Name,Display_Name__c,Section__c,Page__c From Page_Section__c WHERE Page__c IN:pageIds AND Form__c=null ORDER BY Sort_Order__c])
         {
             Page_Section__c psj = pageSec.Clone(false,true);
             //psj.RecordTypeId = Schema.SObjectType.Page_Section__c.getRecordTypeInfosByName().get('Form Page Section').getRecordTypeId();
             psj.Form__c = formID;  
             psj.Root__c =  pageSec.Id;         
             sectionIds.add(pageSec.Section__c);
             pageSecList.add(psj);                     
         }
         
         if(pageSecList.size()>0)
         {
             insert pageSecList;
         }
         
         
         for(Page_Section__c pageSecInserted:[Select Id, Sort_Order__c,Root__c, Name,Display_Name__c,Section__c,Page__c From Page_Section__c WHERE Form__c =:formID ORDER BY Sort_Order__c])
         {
             pageSecOldNewmap.put(pageSecInserted.Root__c,pageSecInserted.Id);
         }
                           
         
         for(Section_Question__c secQuestion:[Select Id, Sort_Order__c,Root__c,Required__c,Name,Section__c,Question__r.Question_Text__c,Question__c From Section_Question__c WHERE Form__c =null AND Section__c IN:sectionIds  ORDER BY Sort_Order__c])
         {
             Section_Question__c secQn = secQuestion.Clone(false,true);
             secQn.Form__c = formID;
             secQn.Root__c =  secQuestion.Id;            
             secQNList.add(secQn);
         }         
         
         if(secQNList.size()>0)
         {
             system.debug ('##secQNList: '+secQNList);
             insert secQNList;
         }
                  
         for(Section_Question__c secQuestion:[Select Id, Name, Sort_Order__c,Root__c,Section__c,Question__r.Question_Text__c,Question__c From Section_Question__c WHERE Form__c =:formID ORDER BY Sort_Order__c])
         {
             secQuesOldNewmap.put(secQuestion.Root__c,secQuestion.Id);             
         }
         
      // This is required to put replace the old section question with new section question for the form
         /*for(Question_Section_Branching__c qnSecBranch:[Select Id, Name,Comparison_Operator__c,Driver__c,Section_Question__c,Driver_Section__c,Question_to_Enable__c,Status__c,Numeric_Comparison_Value__c,Text_Comparison_Value__c FROM Question_Section_Branching__c WHERE Section_Question__c IN:secQuesOldNewmap.keySet() AND Status__c ='Active'])
         {
             Question_Section_Branching__c qsb = qnSecBranch.Clone(false,true);
             qsb.Form__c=formID;
             qsb.Driver_Section__c = pageSecOldNewmap.get(qnSecBranch.Driver_Section__c);

             if(qsb.Driver_Section__c!=null)
             {
             qsb.Section_Question__c = secQuesOldNewmap.get(qnSecBranch.Section_Question__c);
             qsb.Question_to_Enable__c = secQuesOldNewmap.get(qnSecBranch.Question_to_Enable__c); 
             qnSecBranchList.add(qsb);
             }
         }
         
         if(qnSecBranchList.size()>0)
         {
             system.debug ('##qnSecBranchList: '+qnSecBranchList);
             insert qnSecBranchList;
         }*/
       
       }
       
       catch(Exception e)        
       {
           system.debug('Exception '+e);
           Database.rollback(sp);
       }
      } 
     }
    }